require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'

platform :ios, '10.0'

target 'ekwely' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  target 'ekwelyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ekwely-tvOS' do
  # Pods for ekwely-tvOS

  target 'ekwely-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
