const ICONS = {
  messages: 'Messages',
  places: 'Places',
  star: 'Shape',
  comment: 'Comment',
  logout: 'Export',
  feed: 'Feed',
  facbook: 'Facebook',
  wallet: 'Folder',
  bus: 'Group-9924',
  heart: 'Heart',
  settings: 'Settings',
  twitter: 'Twitter',
  instgram: 'Twitter',
  user: 'Union-33',
  qr: 'qrcode-scan',
  menu: 'Feed',
  close: 'close',
  check: 'check',
  checkBox: 'radiobox-blank',
  checkBoxMarked: 'radiobox-marked',
};
export default ICONS;
