const IMAGES = {
  userImage: require('../assets/Images/userImage.png'),
  loginBg: require('../assets/Images/loginBg.png'),
  map: require('../assets/Images/map.png'),
  slider: require('../assets/Images/slider.png'),
  slider1: require('../assets/Images/slider1.png'),
  slider2: require('../assets/Images/slider2.png'),
  slider3: require('../assets/Images/slider3.png'),
  promo: require('../assets/Images/promo.png'),
  close: require('../assets/Images/close.png'),
  favorite: require('../assets/Images/favorite.png'),
  cart: require('../assets/Images/cart.png'),
  search: require('../assets/Images/search.png'),
  p1: require('../assets/Images/p1.png'),
  p2: require('../assets/Images/p2.png'),
  drop: require('../assets/Images/drop.png'),
  instagram: require('../assets/Images/instagram.png'),
  facebook: require('../assets/Images/facebook.png'),
  back: require('../assets/Images/back.png'),
  in: require('../assets/Images/in.png'),
  out: require('../assets/Images/out.png'),
  promoIcon: require('../assets/Images/promoIcon.png'),
};

export default IMAGES;
